// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/monitor/v1/monitor.proto

package monitor

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Monitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Interval      int32                  `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                        // "UP", "DOWN", "PENDING"
	LastCheck     string                 `protobuf:"bytes,6,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"` // Timestamp (string для простоты JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monitor) Reset() {
	*x = Monitor{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitor) ProtoMessage() {}

func (x *Monitor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitor.ProtoReflect.Descriptor instead.
func (*Monitor) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Monitor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Monitor) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Monitor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Monitor) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Monitor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Monitor) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

type CreateMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Interval      int32                  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMonitorRequest) Reset() {
	*x = CreateMonitorRequest{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorRequest) ProtoMessage() {}

func (x *CreateMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorRequest.ProtoReflect.Descriptor instead.
func (*CreateMonitorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMonitorRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateMonitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMonitorRequest) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type CreateMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Возвращаем ID созданного
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMonitorResponse) Reset() {
	*x = CreateMonitorResponse{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorResponse) ProtoMessage() {}

func (x *CreateMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorResponse.ProtoReflect.Descriptor instead.
func (*CreateMonitorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMonitorResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMonitorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorsRequest) Reset() {
	*x = ListMonitorsRequest{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorsRequest) ProtoMessage() {}

func (x *ListMonitorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorsRequest.ProtoReflect.Descriptor instead.
func (*ListMonitorsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{3}
}

type ListMonitorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitors      []*Monitor             `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorsResponse) Reset() {
	*x = ListMonitorsResponse{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorsResponse) ProtoMessage() {}

func (x *ListMonitorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorsResponse.ProtoReflect.Descriptor instead.
func (*ListMonitorsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *ListMonitorsResponse) GetMonitors() []*Monitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

type DeleteMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMonitorRequest) Reset() {
	*x = DeleteMonitorRequest{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorRequest) ProtoMessage() {}

func (x *DeleteMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorRequest.ProtoReflect.Descriptor instead.
func (*DeleteMonitorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMonitorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMonitorResponse) Reset() {
	*x = DeleteMonitorResponse{}
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorResponse) ProtoMessage() {}

func (x *DeleteMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_v1_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorResponse.ProtoReflect.Descriptor instead.
func (*DeleteMonitorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_v1_monitor_proto_rawDescGZIP(), []int{6}
}

var File_api_proto_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_api_proto_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\x1a\x1cgoogle/api/annotations.proto\"\x92\x01\n" +
	"\aMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\x05R\binterval\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"last_check\x18\x06 \x01(\tR\tlastCheck\"X\n" +
	"\x14CreateMonitorRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\x05R\binterval\"'\n" +
	"\x15CreateMonitorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13ListMonitorsRequest\"G\n" +
	"\x14ListMonitorsResponse\x12/\n" +
	"\bmonitors\x18\x01 \x03(\v2\x13.monitor.v1.MonitorR\bmonitors\"&\n" +
	"\x14DeleteMonitorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeleteMonitorResponse2\xd9\x02\n" +
	"\x0eMonitorService\x12m\n" +
	"\rCreateMonitor\x12 .monitor.v1.CreateMonitorRequest\x1a!.monitor.v1.CreateMonitorResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/monitors\x12g\n" +
	"\fListMonitors\x12\x1f.monitor.v1.ListMonitorsRequest\x1a .monitor.v1.ListMonitorsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/monitors\x12o\n" +
	"\rDeleteMonitor\x12 .monitor.v1.DeleteMonitorRequest\x1a!.monitor.v1.DeleteMonitorResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/monitors/{id}B\x1eZ\x1c./pkg/api/monitor/v1;monitorb\x06proto3"

var (
	file_api_proto_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_api_proto_monitor_v1_monitor_proto_rawDescData []byte
)

func file_api_proto_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_api_proto_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_api_proto_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_monitor_v1_monitor_proto_rawDesc), len(file_api_proto_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_api_proto_monitor_v1_monitor_proto_rawDescData
}

var (
	file_api_proto_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
	file_api_proto_monitor_v1_monitor_proto_goTypes  = []any{
		(*Monitor)(nil),               // 0: monitor.v1.Monitor
		(*CreateMonitorRequest)(nil),  // 1: monitor.v1.CreateMonitorRequest
		(*CreateMonitorResponse)(nil), // 2: monitor.v1.CreateMonitorResponse
		(*ListMonitorsRequest)(nil),   // 3: monitor.v1.ListMonitorsRequest
		(*ListMonitorsResponse)(nil),  // 4: monitor.v1.ListMonitorsResponse
		(*DeleteMonitorRequest)(nil),  // 5: monitor.v1.DeleteMonitorRequest
		(*DeleteMonitorResponse)(nil), // 6: monitor.v1.DeleteMonitorResponse
	}
)
var file_api_proto_monitor_v1_monitor_proto_depIdxs = []int32{
	0, // 0: monitor.v1.ListMonitorsResponse.monitors:type_name -> monitor.v1.Monitor
	1, // 1: monitor.v1.MonitorService.CreateMonitor:input_type -> monitor.v1.CreateMonitorRequest
	3, // 2: monitor.v1.MonitorService.ListMonitors:input_type -> monitor.v1.ListMonitorsRequest
	5, // 3: monitor.v1.MonitorService.DeleteMonitor:input_type -> monitor.v1.DeleteMonitorRequest
	2, // 4: monitor.v1.MonitorService.CreateMonitor:output_type -> monitor.v1.CreateMonitorResponse
	4, // 5: monitor.v1.MonitorService.ListMonitors:output_type -> monitor.v1.ListMonitorsResponse
	6, // 6: monitor.v1.MonitorService.DeleteMonitor:output_type -> monitor.v1.DeleteMonitorResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_monitor_v1_monitor_proto_init() }
func file_api_proto_monitor_v1_monitor_proto_init() {
	if File_api_proto_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_monitor_v1_monitor_proto_rawDesc), len(file_api_proto_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_api_proto_monitor_v1_monitor_proto_depIdxs,
		MessageInfos:      file_api_proto_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_api_proto_monitor_v1_monitor_proto = out.File
	file_api_proto_monitor_v1_monitor_proto_goTypes = nil
	file_api_proto_monitor_v1_monitor_proto_depIdxs = nil
}
